[package]
name = "rbac"
version = "0.1.0"
edition = "2021"

[dependencies]
entities = { path = "../entities" }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
serde = { version = "1.0.203", features = ["derive"] }
