[package]
name = "server"
version = "0.1.0"
edition = "2021"
default-run = "server"

[dependencies]
sea-orm = { version = "1.1.19", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
  "macros",
] }
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
entities = { path = "../entities" }
validator = { version = "0.20.0", features = ["derive"] }
argon2 = "0.5.3"
tokio = { version = "1.49.0", features = ["full"] }
axum = "0.8.8"
serde_json = "1.0.148"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
utoipa = { version = "5.4.0", features = ["axum_extras", "uuid"] }
scalar-doc = "0.1.2"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
time = "0.3.44"
reqwest = { version = "0.13.1", features = ["json", "form"] }
